# Generated by Django 3.2.11 on 2022-03-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingapp', '0002_rename_desc_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='description',
        ),
    ]
